version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db/dbname  # Update with your credentials
    volumes:
      - .:/app  # Mount the current directory to the container

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: dbname
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
  
  test:
    build: .
    command: ["pytest", "tests"]  # Adjust the path to your tests if needed
    depends_on:
      - db


volumes:
  db_data:
